name: build
on: [push, pull_request, workflow_dispatch] # disabled for debug
#on: [workflow_dispatch] # disabled for debug
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
        mongodb-version: [4.2, 4.4, 5]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB ${{ matrix.mongodb-version }}    
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:workflow:build
        env:
          TEST_ONLINE: mongodb://localhost:27017/test